---
title: "Conclusion"
---
This study explores potential risk factors for stroke and investigates whether a patient’s likelihood to get a stroke can be predicted by these factors. Through fitting a logistic regression model, age group, hypertension, heart disease, and diabetes status were found to be statistically significant predictors and associated with a higher risk of stroke. To assess the predictive performance of the model via machine learning, a threshold probability of 0.0504 was selected based on the precision versus recall curve plus the goal of the study, and a simple logistic regression model with continuous age being the only predictor was created for comparison purposes. Predicting the stroke events using these two algorithms shows that the more complex model has higher accuracy, specificity, and sensitivity, and thus this model is favored over the simple model.\

The analysis was successful as the identified risk factors are consistent with those suggested by the Centers for Diseases Control and Prevention (CDC) [4] and the accuracy of the predictive model is acceptable. However, this study has several limitations. First, the stroke group is under-represented in the dataset. Thus, the available demographic and clinical data were not balanced between the two groups. The high prevalence of the healthy controls would impair the robustness of the model’s accuracy. Second, to account for group imbalance, this study manually chose a threshold probability based on the precision versus recall curve. Yet, this would weaken the generalizability of this study as this certain threshold probability may work well only for this specific dataset. Third, this study did not test the association between each pair of categorical predictors. For instance, hypertension is a predominant risk factor for cardiovascular disease [8]. Therefore, a more parsimonious logistic regression model could be viable. Lastly, the dataset does not include information on other critical risk factors for stroke such as race, ethnicity, and family history. Thus, the model still lacks the ability to capture all possible predictors for the stroke event.\

A future study should base on a more thorough literature review, from which past prediction methodologies and future directions could be referenced. Moreover, a more group-balanced dataset could be used in future studies. Alternatively, applying a method to control the prevalence would be critical to make the accuracy of the model informative and convincing. Lastly, exploring a way to better graph logistic regression models would help ameliorate data visualization of the study.
